ERROR in line 2:
name "a" already exists in scope
